In [3]:
import numpy as np

# np的版本

In [21]:
np.__version__

'1.20.2'

# np的配置

In [22]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


# np的函数说明

In [26]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

# 1d array

In [4]:
np.array([1,2,3])

array([1, 2, 3])

# 2D 

In [5]:
np.array( [(1,2,3),(2,34,5)] )

array([[ 1,  2,  3],
       [ 2, 34,  5]])

In [9]:
np.array([ [1,2] , [2,3]])


array([[1, 2],
       [2, 3]])

# np.arange(from, to, by )    前闭后开

In [15]:
np.arange(0,14,2)

array([ 0,  2,  4,  6,  8, 10, 12])

## np.arange(single value)      从0开始计数直到 输入值-1  前闭后开

In [58]:
# -1 means unspecify
np.arange(10).reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# np.add()

In [64]:
a1 = np.arange(9).reshape(3,3)
a2 = np.arange(3).reshape(3,1)
a2

array([[0],
       [1],
       [2]])

In [65]:
np.add(a1,a2)

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

# 第一个是行  第二个是列

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# 测试 0  np.all() vs np.any()

In [33]:
np1 = np.zeros((2,3))

np.all(np1)

False

In [34]:
np.any(np1)

False

# 测试 inf 和 nan

In [36]:
a1 = np.array([1,0,np.nan, np.Infinity])
np.isfinite(a1)

array([ True,  True, False, False])

In [37]:
np.isinf(a1)

array([False, False, False,  True])

In [38]:
np.isnan(a1)

array([False, False,  True, False])

# identity matrix

In [39]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])